import type { Metadata } from "next";
import { JetBrains_Mono, Outfit, Syncopate } from "next/font/google";
import "./globals.css";
import Header from "@/components/layout/Header";

const syncopate = Syncopate({
  variable: "--font-heading",
  subsets: ["latin"],
  weight: ["700", "400"],
});

const outfit = Outfit({
  variable: "--font-sans",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
});

const jetbrains = JetBrains_Mono({
  variable: "--font-mono",
  subsets: ["latin"],
  weight: ["400", "500", "700"],
});

export const metadata: Metadata = {
  title: "novodeal",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      style={{
        "--font-heading": syncopate.style.fontFamily,
        "--font-sans": outfit.style.fontFamily,
        "--font-mono": jetbrains.style.fontFamily,
      } as React.CSSProperties}
    >
      <body
        className={`${syncopate.variable} ${outfit.variable} ${jetbrains.variable} antialiased`}
        suppressHydrationWarning
      >
        <Header />
        <main className="w-full min-h-[calc(100vh-20px)] mt-20">
          {children}
        </main>
        {/* <Footer /> */}
      </body>
    </html>
  );
}
